### PR TITLE
fix:: empty trait format bug

### LINKED ISSUE #2008: Minor formatting issue with empty trait definition
**Describe the bug**
For this Clarity code:
```clarity
(define-trait my-trait ())
```

The formatter adds a bunch of unnecessary whitespace:
```clarity
(define-trait my-trait (
  
))
```

**To Reproduce**
Steps to reproduce the behavior, create that contract, then format it using the LSP in VSCode.

**Expected behavior**
The original formatting should be left as-is.

### PR DESCRIPTION
**Pull request by BiliqisO**
### Description

This PR fixes #2008 - Empty trait definitions no longer add unnecessary whitespace.

 
  - I added an early-exit check in the define_trait function (formatter/mod.rs:460-464) to detect
  empty method lists and format them inline without adding whitespace.

  - I added the test_empty_trait test case to verify the fix

### CODE REVIEW

File: components/clarinet-format/src/formatter/mod.rs [hunk 1]
```diff
@@ -453,11 +453,20 @@ impl<'a> Aggregator<'a> {
         // name
         acc.push_str(&self.format_source_exprs(slice::from_ref(&exprs[1]), previous_indentation));
         acc.push_str(" (");
+
+        // methods
+        let methods = exprs[2].match_list().unwrap();
+
+        // if there are no methods, keep it on one line (no whitespace)
+        if methods.is_empty() {
+            acc.push_str("))");
```
Comment (brady-stacks) [inline components/clarinet-format/src/formatter/mod.rs]: this should also handle the case where the methods are followed by comments
```
(define-trait my-trait 
  () ;; empty
)
```

**Comment by brady-stacks** [comment]
Looks good @BiliqisO. If you can add a test for the case I mentioned we can merge it 👍

File: components/clarinet-format/src/formatter/mod.rs (hunk 1 above)
Comment (BiliqisO) [reply components/clarinet-format/src/formatter/mod.rs]: Actually, this fix doesn't account for comments (my bad). I'll make a correction on that now 🙏🏻

**Comment by brady-stacks** [comment]
Sorry @BiliqisO I tried to fix the conflicts in the gh editor and failed. If you can fix those we'll get it merged asap

**Comment by BiliqisO** [comment]
> Sorry @BiliqisO I tried to fix the conflicts in the gh editor and failed. If you can fix those we'll get it merged asap

Okay, I'll do that now
