### PR TITLE
fix: allow multiple lints

### LINKED ISSUE #2144: linter: multiple allow
Multiple lints in an `allow` list aren't recognized properly.

With the Config
```
[repl.analysis.lints] 
noop = "ignore" 
unused_const = "error" 
case_const = "error"
``` 
and contract
```
;; #[allow(unused_const, case_const)]
(define-constant this_is_regular_snake_case u100)
```
You receive the error
```
Remove the illegal character 't'
error: constant `this_is_regular_snake_case` never used
--> contracts/counter.clar:7:1
(define-constant this_is_regular_snake_case u100)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Remove this expression
! 1 warning detected
x 2 errors detected
```

This should pass clarinet check

### PR DESCRIPTION
**Pull request by brady-stacks**
closes #2144

### CODE REVIEW

File: components/clarity-repl/src/analysis/lints/mod.rs [hunk 1]
```diff
@@ -17,3 +17,39 @@ pub use unused_map::UnusedMap;
...
+    use crate::analysis::linter::{Lint, LintLevel};
+    use crate::repl::session::Session;
+    use crate::repl::SessionSettings;
+
+    #[test]
+    fn allow_with_annotation_at_error_level() {
+        #[rustfmt::skip]
+        let snippet = indoc!("
+        ;; #[allow(unused_const, case_const)]
+        (define-constant this_is_regular_snake_case u100)
```
Comment (jbencin-stacks) [inline components/clarity-repl/src/analysis/lints/mod.rs]: Indent:

```suggestion
            ;; #[allow(unused_const, case_const)]
            (define-constant this_is_regular_snake_case u100)
```
