### PR TITLE
fix: commented-out function params

### LINKED ISSUE #1892: Comment edited by clarity formatter
**Describe the bug**

It's not supposed to update comments.

**To Reproduce**

```clarity
      ;; /g/'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token/base_contract_sbtc
      (try! (contract-call? 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token
        ;; /g/.aibtc-pre-faktory/dao_contract_token_prelaunch
        transfer pre-fee tx-sender .aibtc-pre-faktory none
      ))
```

After save:
```clarity
      ;; /g/'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token/base_contract_sbtc
      (try! (contract-call? 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token
        ;; /g/.aibtc-pre-faktory/dao_contract_token_prelaunch transfer pre-fee
        tx-sender .aibtc-pre-faktory none
      ))
```

Which results in a few params getting commented out as indicated by the big red squigglies:
```
contract 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token' has no public function 'tx-sender 'clarity`
```

or through `clarinet check`

```
error: contract 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token' has no public function 'tx-sender'
--> contracts/dao/token/aibtc-faktory-dex.clar:70:13
      (try! (contract-call? 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token
            ^
```

**Expected behavior**

Leave the comments as they represent template values replaced in the next line.

**Environment (please complete the following information):**
 - clarinet 3.1.0

**Additional context**

Will try upgrading to latest locally but suspect it's an edge case given it's worked really well everywhere else I had the comments.

### LINKED ISSUE #2188: Formatter: commented-out function params
When you have a function like:

```clarity
(define-public (some-fn
        (a uint)
        (b uint)
    )
    (ok true)
)
```

If you comment out one of the function parameters, it bumps it up to the previous line.

```clarity
(define-public (some-fn
        (a uint);; (b uint)
    )
    (ok true)
)
```

This also means you can't have a comment line to "document" a parameter, as it'll get moved up.

```clarity
(define-public (some-fn
        (a uint);; I want to comment `b` but it moves up << // after formatting //
        ;; I want to comment `b` but it moves up << // before formatting //
        (b uint)
    )
    (ok true)
)
```

Not a big deal at all, just wanted to flag it!

### PR DESCRIPTION
**Pull request by brady-stacks**
- closes #2188 
- closes #1892 (similar comment bug)

### CODE REVIEW

File: components/clarinet-format/src/formatter/mod.rs [hunk 1]
```diff
@@ -1613,13 +1612,16 @@ impl<'a> Aggregator<'a> {
             if let Some((name, args)) = def.split_first() {
                 acc.push_str(&self.display_pse(name, ""));
 
+                let args_indent = format!("{indentation}{indentation}");
```
Comment (xoloki-stacks) [inline components/clarinet-format/src/formatter/mod.rs:1615]: Did moving this here have an effect?  It wasn't obvious to me that it would.

Comment (brady-stacks) [reply components/clarinet-format/src/formatter/mod.rs:1615]: moved it because it was defined too broadly. Wasn't used outside of this scope anyway
