### PR TITLE
fix::broken Tx helper deployContract

### LINKED ISSUE #1993: Tx helper deployContract broken
**Describe the bug**
using 
```
tx.deployContract(
      "oktrue",
      "(define-public (ot) (ok stacks-block-height))",
      {
        clarityVersion: 3,
      },
     simnet.deployer)
``` 
results in an error around the ContractOptions. Same for `null`

### PR DESCRIPTION
**Pull request by BiliqisO**
### Description

Fixes #1993 
Added deployContract handling in mineBlock in the node/src/sdkProxy.ts and browser/src/sdkProxy.ts files
I also fixed the typo in common/src/sdkProxyHelper.ts file

### CODE REVIEW

**Review by hugo-stacks — CHANGES_REQUESTED** [review]
Thanks @BiliqisO 
Looking good.
Can you add an unit test in components/clarinet-sdk/node/tests/simnet-usage.test.ts?

**Comment by BiliqisO** [comment]
I made a couple of updates to the fix. The test caught a JSON deserialization issue with the clarityVersion....
I implemented a custom serde deserializer for clarityVersion to maintain type safety while accepting JSON input
I also made the options field optional so it can properly account for null values from JS.

File: components/clarinet-sdk/node/src/sdkProxy.ts [hunk 1]
```diff
@@ -27,22 +27,22 @@ type RunSnippet = SDK["runSnippet"];
...
+  ? DeployContract
+  : K extends "transferSTX"
+  ? TransferSTX
+  : K extends "mineBlock"
+  ? MineBlock
+  : K extends "getDataVar"
+  ? GetDataVar
+  : K extends "getMapEntry"
+  ? GetMapEntry
+  : SDK[K];
```
Comment (hugo-stacks) [inline components/clarinet-sdk/node/src/sdkProxy.ts]: The previous formatting isn't the best, but that's how prettier formats it by default.
Could you revert it?

File: components/clarinet-sdk/node/src/sdkProxy.ts [hunk 2]
```diff
@@ -120,6 +120,14 @@ export function getSessionProxy() {
                 },
               };
             }
+            if (tx.deployContract) {
+
```
Comment (hugo-stacks) [inline components/clarinet-sdk/node/src/sdkProxy.ts]: extra line

File: components/clarinet-sdk/node/tests/simnet-usage.test.ts [hunk 3]
```diff
@@ -475,6 +475,42 @@ describe("simnet can get contracts info and deploy contracts", () => {
...
+    const [deployRes] = simnet.mineBlock([
+      tx.deployContract("oktrue", source, { clarityVersion: 3 }, simnet.deployer),
+    ]);
+
+    expect(deployRes.result).toStrictEqual(Cl.bool(true));
+
+    const contractInterface = simnet.getContractsInterfaces().get(`${simnet.deployer}.oktrue`)!;
+    expect(contractInterface.clarity_version).toBe("Clarity3");
+
+
```
Comment (hugo-stacks) [inline components/clarinet-sdk/node/tests/simnet-usage.test.ts]: extra lines

File: components/clarinet-sdk-wasm/src/core.rs [hunk 4]
```diff
@@ -154,20 +177,23 @@ impl ContractOptions {
...
-    options: ContractOptions,
-    sender: String,
+    #[wasm_bindgen(skip)]
+    pub name: String,
+    #[wasm_bindgen(skip)]
+    pub content: String,
+    #[wasm_bindgen(skip)]
+    pub options: Option<ContractOptions>,
+    #[wasm_bindgen(skip)]
+    pub sender: String,
```
Comment (hugo-stacks) [inline components/clarinet-sdk-wasm/src/core.rs]: Why do we need to `skip` here? 🤔

File: components/clarinet-sdk-wasm/src/core.rs [hunk 5]
```diff
@@ -133,10 +133,33 @@ impl CallFnArgs {
...
+        Some(1) => ClarityVersion::Clarity1,
+        Some(2) => ClarityVersion::Clarity2,
+        Some(3) => ClarityVersion::Clarity3,
+        Some(4) => ClarityVersion::Clarity4,
+        Some(v) => {
+            log!("Invalid clarity version {v}. Using default version.");
+            DEFAULT_CLARITY_VERSION
+        }
+        None => DEFAULT_CLARITY_VERSION,
+    })
```
Comment (hugo-stacks) [inline components/clarinet-sdk-wasm/src/core.rs]: Would it be able to factorize this with the ContractOptions constructor?
This kind of duplicate logic makes it harder for us to support new clarity versions in the future

**Review by hugo-stacks — CHANGES_REQUESTED** [review]
Thanks @BiliqisO 
That's great. Left a few comments.
It makes me realize that the formatting for TS code isn't properly set in the CI, but until we can fix, can you please take a look at the formatting comments I left?
ty 🙏

File: components/clarinet-sdk-wasm/src/core.rs (hunk 4 above)
Comment (BiliqisO) [reply components/clarinet-sdk-wasm/src/core.rs]: Oh, I was getting these errors 👇🏼 when I tried to compile after changing the struct field data visibility to public, I changed them to public because I thought it needed to be so I can test for tx.deployContract. On removing them and running the tests now, I realised that there was no need for that in the first place.

```
error[E0277]: the trait bound `std::string::String:                  
    std::marker::Copy` is not satisfied
       --> components/clarinet-sdk-wasm/src/core.rs:189:15
        |
    187 | #[wasm_bindgen]
        | --------------- in this procedural macro expansion
    188 | pub struct DeployContractArgs {
    189 |     pub name: String,
        |               ^^^^^^ the trait `std::marker::Copy` is not
    implemented for `std::string::String`
        |
    note: required by a bound in
    `__wbg_get_deploycontractargs_name::assert_copy`
       --> components/clarinet-sdk-wasm/src/core.rs:187:1
        |
    187 | #[wasm_bindgen]
        | ^^^^^^^^^^^^^^^ required by this bound in `assert_copy`
        = note: this error originates in the derive macro
    `::wasm_bindgen::__rt::BindgenedStruct` (in Nightly builds, run with
    -Z macro-backtrace for more info)

    error[E0277]: the trait bound `std::string::String:
    std::marker::Copy` is not satisfied
       --> components/clarinet-sdk-wasm/src/core.rs:190:18
        |
    187 | #[wasm_bindgen]
        | --------------- in this procedural macro expansion
    ...
    190 |     pub content: String,
        |                  ^^^^^^ the trait `std::marker::Copy` is not
    implemented for `std::string::String`
        |
    note: required by a bound in
    `__wbg_get_deploycontractargs_content::assert_copy`
       --> components/clarinet-sdk-wasm/src/core.rs:187:1
        |
    187 | #[wasm_bindgen]
        | ^^^^^^^^^^^^^^^ required by this bound in `assert_copy`
        = note: this error originates in the derive macro
    `::wasm_bindgen::__rt::BindgenedStruct` (in Nightly builds, run with
    -Z macro-backtrace for more info)

    error[E0277]: the trait bound `ContractOptions: std::marker::Copy` is
     not satisfied
       --> components/clarinet-sdk-wasm/src/core.rs:191:40
        |
    187 | #[wasm_bindgen]
        | --------------- in this procedural macro expansion
    ...
    191 |     pub options: Option<ContractOptions>,
        |                                        ^ the trait
    `std::marker::Copy` is not implemented for `ContractOptions`
    ```

**Comment by hugo-stacks** [comment]
Looking good @BiliqisO, thanks for the quick rework - i'll re-review in the morning

Note that the repo now needs requires this: "Commits must have verified signatures."
You may need to setup verified commits and sign all the commits of this PR
