### PR TITLE
fix: rework format-ignore

### LINKED ISSUE #2105: `@format-ignore` break formatting
The format-ignore directive seems to mess up the parent function:

input
```clar
(define-public (hello)
  (begin
    ;; @format-ignore
    (ok "world")
  )
)
```

`clarinet fmt --in-place` ouput:
```clar
(
  define-public   (hello)
  (
  begin
  ;; @format-ignore
  (ok "world")
)
)
```

### PR DESCRIPTION
**Pull request by brady-stacks**
closes #2105 

This is a somewhat heavy rework of format-ignore to cache ignored exprs within the main loop. I'm not sure it ever worked since we were only checking at the top level above function signatures.

### CODE REVIEW

File: components/clarinet-format/src/formatter/ignored.rs [hunk 1]
```diff
@@ -1,64 +1,85 @@
 use clarity::vm::representations::PreSymbolicExpression;
 
+fn u32_to_usize(val: u32) -> usize {
+    usize::try_from(val).unwrap()
+}
+
+/// spans use 1-based index, this const is largely only for this comment
```
Comment (xoloki-stacks) [inline components/clarinet-format/src/formatter/ignored.rs:7]: It's unclear what you mean by `this const is largely only for this comment`.  The plain reading is that the `const` is not used, but it is used in multiple places.  If you meant that the `const` is only used to convert a colums to an index (which the code seems to indicate), then maybe you should rewrite the comment to make it more clear?

File: components/clarinet-format/src/formatter/ignored.rs [hunk 2]
```diff
@@ -1,64 +1,85 @@
...
+    for line_idx in start_line..=end_line {
+        if line_idx > lines.len() {
+            break;
         }
 
-        if idx == 0 {
-            // First line (the one with the opening parenthesis)
-            if let Some(paren_pos) = line.find('(') {
-                result.push_str(&line[paren_pos..]);
+        let line = lines[line_idx - COLUMN_TO_INDEX_OFFSET];
```
Comment (xoloki-stacks) [inline components/clarinet-format/src/formatter/ignored.rs:42]: Here again the usage of `COLUMN_TO_INDEX_OFFSET` is really unclear.  I would have expected it to be used when dealing with `start_column`/`end_column`, not `line_idx`.  

Maybe both lines and columns are 1-based?  If so, `COLUMN_TO_INDEX_OFFSET` needs to be renamed.

File: components/clarinet-format/src/formatter/mod.rs [hunk 3]
```diff
@@ -929,8 +1142,10 @@ impl<'a> Aggregator<'a> {
 
         // body expressions
         let mut prev_end_line = None;
-        for e in exprs.get(3..).unwrap_or_default() {
+        let body_exprs = exprs.get(3..).unwrap_or_default();
```
Comment (xoloki-stacks) [inline components/clarinet-format/src/formatter/mod.rs:1145]: It's really not obvious to me where the magic number `3` comes from here.  It was in the previous code, so I don't think it's wrong, but it would be helpful for people unfamiliar with this code to explain why you need to pop the first few tokens to get`body_exprs`.

**Review by xoloki-stacks — APPROVED** [review]
I don't think there's anything wrong with this code, so I'm going to approve it in the service of getting it out the door tomorrow.  But it would be helpful in this or a follow-on PR to address my comments in regards to naming of `COLUMN_TO_INDEX_OFFSET` and the number of tokens to pop in `body_exprs`.

**Comment by hugo-stacks** [comment]
Thanks for the thorough review @xoloki-stacks 
I need to mark comments as resolved i order to merge this PR.
So for the record, here are the links to the comments in case it's not obvious to find them once resolved:
- https://github.com/stx-labs/clarinet/pull/2110#discussion_r2629133720
- https://github.com/stx-labs/clarinet/pull/2110#discussion_r2629139558
- https://github.com/stx-labs/clarinet/pull/2110#discussion_r2629150417

@brady-stacks

File: components/clarinet-format/src/formatter/mod.rs (hunk 3 above)
Comment (brady-stacks) [reply components/clarinet-format/src/formatter/mod.rs:1145]: above this we have the 1 and 2
```
        // asset-owner
        acc.push_str(&self.format_source_exprs(slice::from_ref(&exprs[1]), previous_indentation));

        // allowances
        if let Some(allowances_list) = exprs.get(2) {
```
The entirety of the PSE list should probably be parsed into a new structure in its own pass, but currently it's doing this indexing junk ☹️
