### PR TITLE
 fix(devnet): implement graceful shutdown for SIGTERM signals

### LINKED ISSUE #1391: Sending SIGINT/SIGTERM to the process started by clarinet dev start doesn't trigger a graceful shutdown
**Describe the bug**
When sending a SIGINT or SIGTERM to the clarinet process spawned when executing `clarinet dev start` does not trigger a graceful shutdown. Instead, it kills the process ungracefully

**To Reproduce**
1. Run `clarinet dev start`
2. Run `ps -a | grep clarinet` in another terminal session and grab the PID
3. Run `kill -TERM <PID>` or `kill -INT <PID>`

**Expected behavior**
The clarinet process should trigger a graceful shutdown whenever SIGINT or SIGTERM signals are received

**Environment (please complete the following information):**
 - OS (version): MacOS Ventura 13.2
 - Docker version: Orbstack latest version
 - Clarinet version: 2.2.1

### PR DESCRIPTION
**Pull request by BiliqisO**
### Description
This PR fixes #1391 

I basically added a signal handler for SIGTERM that forwards to the existing SIGINT graceful shutdown mechanism. 

#### Breaking change?
No

### Example

---

### Checklist

[https://drive.google.com/file/d/1dgbkJ4w68xTo-EZX6U9gh2lodIhy2Qqv/view?usp=drivesdk](url)
[https://drive.google.com/file/d/1qiCKPziM8CJK6zzbz9itKAzMU6BVnUj8/view?usp=drivesdk](url)

### CODE REVIEW

**Comment by hugoclrd** [comment]
Hey @BiliqisO, looks like this PR includes some unwanted commits that have already been merged.
It messes with the files changes makes the PR hard to review.
Can you please fix the history?

**Comment by BiliqisO** [comment]
Hi, I have fixed the history.

**Comment by BiliqisO** [comment]
Hello, The CI workflow tests are failing because of windows compatibility, 
So i was thinking of adding this ctrlc library option for windows compatiblity or just leave it out and allow for windows users to make use of the normal command + c command
What do you think?
```
   #[cfg(windows)]
        {
            if let Err(e) = ctrlc::set_handler(move || {}) {
                eprintln!("Failed to setup signal handler: {}", e);
            }
        }
````

**Comment by hugoclrd** [comment]
Hey @BiliqisO,
So the devnet is already relying on ctrlc [here](https://github.com/hirosystems/clarinet/blob/5c10c0c51327f6e3e3063fd8c5f317ff861aec6d/components/stacks-network/src/lib.rs#L264-L270) and also has [this implementation](https://github.com/hirosystems/clarinet/blob/5c10c0c51327f6e3e3063fd8c5f317ff861aec6d/components/stacks-network/src/ui/mod.rs#L126-L139) to be stopped.
They respectively handle the "--no-dashboard" and "normal" modes.

You might want to build on top of this to properly handle SIGTERM and SIGINT in all situations

File: components/stacks-network/src/lib.rs [hunk 1]
```diff
@@ -259,16 +331,13 @@ async fn do_run_devnet(
...
-        let moved_observer_command_tx = observer_command_tx;
-        let moved_mining_command_tx = mining_command_tx;
-        let _ = ctrlc::set_handler(move || {
-            let _ = moved_orchestrator_terminator_tx.send(true);
-            let _ = moved_observer_command_tx.send(ObserverCommand::Terminate);
-            let _ = moved_mining_command_tx.send(BitcoinMiningCommand::Pause);
-            sleep(Duration::from_secs(3));
-            let _ = devnet_events_tx.send(DevnetEvent::Terminate);
-        });
+        // Set up signal handlers for graceful shutdown (SIGINT and SIGTERM)
```
Comment (tippenein) [inline components/stacks-network/src/lib.rs]: Could we move the `setup_signal_handlers` above the `if` and remove the `else` here? It looks functionally the same without the duplication

Comment (BiliqisO) [reply components/stacks-network/src/lib.rs]: ✅

Comment (tippenein) [reply components/stacks-network/src/lib.rs]: Thanks!

**Comment by tippenein** [comment]
@BiliqisO You can run `cargo clippy --workspace --exclude clarinet-sdk-wasm` to fix up the lint warnings. I think this looks pretty good though!
